### ISSUE TITLE
在不同的包里进行初始化时没办法使用

### ISSUE THREAD

**Issue by huang-aaron** [yanyiwu/gojieba#12]
在同一个包里操作时，可以使用，但我项目里有一个初始化包
将 NewJieba放在初始化包里初始化，其它包调用这个*Jieba对象时出错
错误信息
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x34b6808 pc=0x9b9b8a]

runtime stack:
runtime.throw(0xafb348, 0x2a)
	/data/go/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
	/data/go/src/runtime/sigpanic_unix.go:12 +0x2cc

goroutine 285 [syscall, locked to thread]:
runtime.cgocall(0x9a8630, 0xc4206d7518, 0xc400000000)
	/data/go/src/runtime/cgocall.go:131 +0x110 fp=0xc4206d74d0 sp=0xc4206d7490
github.com/yanyiwu/gojieba._Cfunc_ExtractWithWeight(0x20b75f0, 0x7f5be80008c0, 0x4, 0x0)
	??:0 +0x4e fp=0xc4206d7518 sp=0xc4206d74d0
github.com/yanyiwu/gojieba.(*Jieba).ExtractWithWeight(0xc42002e4d0, 0xc420c48300, 0x27, 0x4, 0x0, 0x0, 0x0)
	/data/gowork/src/github.com/yanyiwu/gojieba/jieba.go:130 +0x10c fp=0xc4206d7588 sp=0xc4206d7518

**Comment by yanyiwu** [comment]
能给一下具体代码吗？方便定位问题

**Comment by huang-aaron** [comment]
```
package main

import (
	"fmt"
	"test/jieba"
)

func main() {
	jieba.Init()
	s := "武汉长江大桥"
	keywords := jieba.X.ExtractWithWeight(s, 5)
	fmt.Println("Extract:", keywords)
}
```
pakage jieba 这个用来初始化对象

```
package jieba

import (
	"github.com/yanyiwu/gojieba"
)

var X *gojieba.Jieba

func Init() {
	X = gojieba.NewJieba()
	defer X.Free()
}
```

**Comment by admpub** [comment]
问题在于Init执行完毕后已经进行了Free，你这种情况应该把X.Free移到函数main中吧

**Comment by huang-aaron** [comment]
@admpub  嗯，是的，代码放上来我就发现了，汗。
还是谢谢你哦
