### ISSUE TITLE
NewJieba如果只想要自定义用户词表，能否只传参用户词表的文件地址，其余使用默认值呢。目前如果只传参用户词表，会报错

### ISSUE THREAD

**Issue by ivory2406** [yanyiwu/gojieba#121]
```
import (
	"github.com/yanyiwu/gojieba"
)

	jbt.jieba = gojieba.NewJieba(
		"",
		"",
		"../data/user.dict.utf8",
		"",
		"")
```
----
报错信息见下，感谢您：
2024-08-28 20:19:17 /root/.go/go1.21.6/pkg/mod/github.com/yanyiwu/gojieba@v1.4.1/deps/cppjieba/include/cppjieba/DictTrie.hpp:212 FATAL exp: [ifs.is_open()] false. open  failed.
SIGABRT: abort
PC=0x7f71b51c5acf m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 6 [syscall]:
runtime.cgocall(0x517900, 0xc000075c78)
        /root/.go/go1.20/src/runtime/cgocall.go:157 +0x5c fp=0xc000075c50 sp=0xc000075c18 pc=0x40c6bc
github.com/yanyiwu/gojieba._Cfunc_NewJieba(0x23b5470, 0x23b5490, 0x23b54b0, 0x23b54d0, 0x23b54f0)
        _cgo_gotypes.go:251 +0x4d fp=0xc000075c78 sp=0xc000075c50 pc=0x51394d
github.com/yanyiwu/gojieba.NewJieba({0xc000075e08?, 0x415830?, 0x0?})
        /root/.go/go1.21.6/pkg/mod/github.com/yanyiwu/gojieba@v1.4.1/jieba.go:40 +0x296 fp=0xc000075dc8 sp=0xc000075c78 pc=0x513dd6

**Comment by yanyiwu** [comment]
不错的建议，在v1.4.2版本里支持了。你试试使用 v1.4.2 预期就可以了。
demo代码可以参考：https://github.com/yanyiwu/gojieba-demo

**Comment by ivory2406** [comment]
特别想给作者加鸡腿，万分感谢，更新到 v1.4.2 ，已经可以用啦🌹
