### ISSUE TITLE
使用範例出現多個「not defined」 Error

### ISSUE THREAD

**Issue by Starfine** [yanyiwu/gojieba#14]
github.com/yanyiwu/gojieba(.text): _ZNSt13basic_filebufIcSt11char_traitsIcEED1Ev: not defined
github.com/yanyiwu/gojieba(.text): _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1ESt13_Ios_Openmode: not defined
github.com/yanyiwu/gojieba(.text): _ZSt16__ostream_insertIcSt11char_traitsIcEERSt13basic_ostreamIT_T0_ES6_PKS3_x: not defined
github.com/yanyiwu/gojieba(.text): _ZSt16__ostream_insertIcSt11char_traitsIcEERSt13basic_ostreamIT_T0_ES6_PKS3_x: not defined
github.com/yanyiwu/gojieba(.text): _ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc: not defined
github.com/yanyiwu/gojieba(.text): _ZSt16__ostream_insertIcSt11char_traitsIcEERSt13basic_ostreamIT_T0_ES6_PKS3_x: not defined
C:\Go\pkg\tool\windows_amd64\link.exe: too many errors
exit status 2

**Comment by Starfine** [comment]
經測試，使用 Visual Studio Code 的 Go 套件才會出現此問題
若用 cmd.exe 直接執行則可正常執行
不知原因為何…？

**Comment by yanyiwu** [comment]
@Starfine 具体原因我也不知道，但是提醒一下，gojieba 底层是用 c++写的，在 linux 上表现没问题，在 windows 上可能有一些问题需要处理。
