### ISSUE TITLE
Readme中bleve示例代码运行时出错

### ISSUE THREAD

**Issue by elprup** [yanyiwu/gojieba#16]
出错提示： `panic: error building tokenizer: config idf not found`

原因：在AddCustomTokenizer函数中缺少了idf和stop_words参数，建议加上

```
    err := indexMapping.AddCustomTokenizer("gojieba",
        map[string]interface{}{
            "dictpath":     gojieba.DICT_PATH,
            "hmmpath":      gojieba.HMM_PATH,
            "userdictpath": gojieba.USER_DICT_PATH,
            "idf":          gojieba.IDF_PATH,
            "stop_words":   gojieba.STOP_WORDS_PATH,
            "type":         "gojieba",
        },
    )
```

**Comment by yanyiwu** [comment]
@elprup 提个 pull request 吧多谢

**Comment by kerneltravel** [comment]
还有提示另外一个错误：
`
package main


import (

    "fmt"

    "os"


    "github.com/blevesearch/bleve"

    "github.com/yanyiwu/gojieba"

    //    _ "github.com/yanyiwu/gojieba/bleve"

)


func Example() {

    INDEX_DIR := "gojieba.bleve"

    messages := []struct {

        Id   string

        Body string

    }{

        {

            Id:   "1",

            Body: "你好",

        },

        {

            Id:   "2",

            Body: "世界",

        },

        {

            Id:   "3",

            Body: "亲口",

        },

        {

            Id:   "4",

            Body: "交代",

        },

    }


    indexMapping := bleve.NewIndexMapping()

    os.RemoveAll(INDEX_DIR)

    // clean index when example finished

    defer os.RemoveAll(INDEX_DIR)


    err := indexMapping.AddCustomTokenizer("gojieba",

        map[string]interface{}{

            "dictpath":     gojieba.DICT_PATH,

            "hmmpath":      gojieba.HMM_PATH,

            "userdictpath": gojieba.USER_DICT_PATH,

            "type":         "gojieba",

            "idf":          gojieba.IDF_PATH,

            "stop_words":   gojieba.STOP_WORDS_PATH,

        },

    )

    if err != nil {

        panic(err)

    }

    err = indexMapping.AddCustomAnalyzer("gojieba",

        map[string]interface{}{

            "type":      "gojieba",

            "tokenizer": "gojieba",

        },

    )

    if err != nil {

        panic(err)

    }

    indexMapping.DefaultAnalyzer = "gojieba"


    index, err := bleve.New(INDEX_DIR, indexMapping)

    if err != nil {

        panic(err)

    }

    for _, msg := range messages {

        if err := index.Index(msg.Id, msg); err != nil {

            panic(err)

        }

    }


    querys := []string{

        "你好世界",

        "亲口交代",

    }


    for _, q := range querys {

        req := bleve.NewSearchRequest(bleve.NewQueryStringQuery(q))

        req.Highlight = bleve.NewHighlight()

        res, err := index.Search(req)

        if err != nil {

            panic(err)

        }

        fmt.Println(res)

    }

}


func main() {

    Example()

}`
go build 通过。
运行时提示
`panic: no tokenizer with name or type 'gojieba' registered`
