### ISSUE TITLE
能否写个bleve的analyzer？

### ISSUE THREAD

**Issue by dearchun** [yanyiwu/gojieba#2]

**Comment by yanyiwu** [comment]
好建议。找个时间支持起来。

**Comment by yanyiwu** [comment]
@zhangchun  刚跑通了代码，https://github.com/yanyiwu/gojieba/blob/master/example/bleve/bleve_gojieba_demo.go 你试试？
目前来说还没足够完善，只是简单的精确模式的分词。只算是能初步使用而已。

**Comment by zhangchun** [comment]
好的，我先用着先，谢谢。

**Comment by atom992** [comment]
+1
