### ISSUE TITLE
deps/cppjieba/DictTrie.hpp:153 FATAL exp: [ifs.is_open()] false. open 

### ISSUE THREAD

**Issue by sinmahod** [yanyiwu/gojieba#20]
您好，项目导入了您的gojieba包，但是运行出错，win7 64位，请问这是什么原因？
gcc用的是mingw-w64  版本：x86_64-6.3.0-release-posix-seh-rt_v5-rev1

```
./deps/cppjieba/DictTrie.hpp:153 FATAL exp: [ifs.is_open()] false. open /workspace/goWorkSpace/src/github.com/yanyiwu/gojieba/dict/jieba.dict.utf8 failed.

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

**Comment by yanyiwu** [comment]
./deps/cppjieba/DictTrie.hpp:153 FATAL exp: [ifs.is_open()] false. open /workspace/goWorkSpace/src/github.com/yanyiwu/gojieba/dict/jieba.dict.utf8 failed.
 日志里面说的很清楚啊，就是找不到 /workspace/goWorkSpace/src/github.com/yanyiwu/gojieba/dict/jieba.dict.utf8 这个文件

**Comment by sinmahod** [comment]
谢谢作者了，昨天我懵了，windows这边报错我去mac上面找发现确实有这个文件。。。脑袋没有反应过来忘记了把路径写死了。
