### ISSUE TITLE
运行例子，直接报 signal: killed 

### ISSUE THREAD

**Issue by xinzf** [yanyiwu/gojieba#24]
运行例子，直接报 signal: killed ，请问是什么原因呢？

**Comment by yanyiwu** [comment]
内存不够？

**Comment by zituocn** [comment]
新版macox问题，把go更新到最新版本

**Comment by songtianyi** [comment]
@zituocn 
哪个版本？1.8.1都不行。

**Comment by xinzf** [comment]
1.8 mac64

不行

**Comment by yanyiwu** [comment]
https://github.com/golang/go/issues/19734

@songtianyi @xinzf 看这个issue是说升级到 1.8.1 就修复了。不行吗？

**Comment by songtianyi** [comment]
@yanyiwu 
issue里好像说的是改cgo的编译参数

**Comment by songtianyi** [comment]
@yanyiwu 
ok了，我更新到了

> go version go1.8.3 darwin/amd64
