### ISSUE TITLE
添加新词山东后反而切词错误了

### ISSUE THREAD

**Issue by magicleo** [yanyiwu/gojieba#27]
package main

import (
	"fmt"
	"strings"

	"github.com/yanyiwu/gojieba"
)

func main() {
	var s string
	var words []string
	x := gojieba.NewJieba()
	defer x.Free()
	s = "山东苹果"
	words = x.Cut(s, false)
	fmt.Println("cut:", strings.Join(words, "/"))
	x.AddWord("山东")
	words = x.Cut(s, false)
	fmt.Println("cut:", strings.Join(words, "/"))

}

输出
cut: 山东/苹果
cut: 山/东/苹果

可见我主动添加了山东这个词，反倒引起了切词的失败？

**Comment by magicleo** [comment]
package main

import (
	"fmt"
	"strings"

	"github.com/yanyiwu/gojieba"
)

func main() {
	var s string
	var words []string
	x := gojieba.NewJieba()
	defer x.Free()
	s = "山东"
	words = x.Cut(s, false)
	fmt.Println("cut:", strings.Join(words, "/"))

	x.AddWord("山东")
	words = x.Cut(s, false)
	fmt.Println("cut:", strings.Join(words, "/"))

	s = "徐世六"

	words = x.Cut(s, false)
	fmt.Println("cut:", strings.Join(words, "/"))
	x.AddWord("徐世六")

	words = x.Cut(s, false)
	fmt.Println("cut:", strings.Join(words, "/"))
}

输出：
cut: 山东
cut: 山/东
cut: 徐/世/六
cut: 徐世六

**Comment by yanyiwu** [comment]
确实AddWord 这个api似乎有点不对劲，但是目前还没发现具体原因，建议直接使用载入默认词典就好了。如果需要更新词典，就更新默认词典就好。

**Comment by dengyuning** [comment]
这个问题现在解决了吗？我今天试了下，好像还是不行。

**Comment by Lofanmi** [comment]
确实很奇怪。

我加了“速来”这个词（进群！速来，晚点没了！），加了没生效；

自己加了词库权重100000，分词可以识别“速来”；

如果不用词库，用AddWord("速来")，没生效。
