### ISSUE TITLE
What is the license of this package?

### ISSUE THREAD

**Issue by windoze** [yanyiwu/gojieba#28]
I can see a MIT license badge in README, but cannot find LICENSE file in the repo.
Could you please clarify?

Thanks.

**Comment by yanyiwu** [comment]
@windoze you can click the badge to find the LICENSE file (https://yanyiwu.mit-license.org/)

**Comment by matryer** [comment]
@windoze Please consider adding a LICENSE file, it's kind of become the standard way of representing the licenses in Github.

Example: https://github.com/matryer/is/blob/master/LICENSE
