### ISSUE TITLE
跨平台编译

### ISSUE THREAD

**Issue by zhaochenxiao90** [yanyiwu/gojieba#4]
这个没有办法跨平台编译吗。我在Mac上想编译成Linux上使用的，你这个怎么做呢

**Comment by yanyiwu** [comment]
已QQ 沟通，目前 gojieba 可能不支持这样的交叉编译。

**Comment by oldcai** [comment]
能告知具体原因吗，看看能不能一起解决？

**Comment by yanyiwu** [comment]
@oldcai 主要原因是 gojieba 底层是 c++写的
