### ISSUE TITLE
godep后找不到文件

### ISSUE THREAD

**Issue by ALEX-yinhao** [yanyiwu/gojieba#41]
../vendor/github.com/yanyiwu/gojieba/jieba.cpp:5:10: fatal error: 'cppjieba/Jieba.hpp' file not found

godep之后报文件不存在

**Comment by xusk** [comment]
相对目录错误吧。在gojieba/deps/cppjieba、gojieba/deps/limonp 我是改了源码的引入包路径。

**Comment by naiba** [comment]
dep 没有吧 deps 目录下载下来。。。。
