### ISSUE TITLE
与python版jieba分词结果不一致

### ISSUE THREAD

**Issue by TinaSummer** [yanyiwu/gojieba#44]
请问为什么与python的jieba分词结果不一致呢？我看python的dict.txt与gojieba的文件jieba.dict.utf8几乎差不多，但是分词结果不一致导致线上线下无法保持一致性

**Comment by JohnnyXu** [comment]
> 请问为什么与python的jieba分词结果不一致呢？我看python的dict.txt与gojieba的文件jieba.dict.utf8几乎差不多，但是分词结果不一致导致线上线下无法保持一致性

我也出现了同样问题, 发现这个gojieba是基于cppjieba开发的, 目测是cppjieba与python的jieba不一致

**Comment by DaiJitao** [comment]
为什么不一致呢？
