### ISSUE TITLE
安装后运行不成功啊。

### ISSUE THREAD

**Issue by Whitehairtoomuch** [yanyiwu/gojieba#5]
报这个错：2016-08-19 10:17:27 ./deps/cppjieba/DictTrie.hpp:153 FATAL exp: [ifs.is_open()] false. open /Users/hqw/Desktop:/Users/hqw/Desktop/gofiles/src/github.com/yanyiwu/gojieba/dict/jieba.dict.utf8 failed.
SIGABRT: abort
PC=0x7fff8aead866 m=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x40b6290, 0xc82004dca8, 0xc800000000)
	/usr/local/go/src/runtime/cgocall.go:123 +0x11b fp=0xc82004dc70 sp=0xc82004dc40
github.com/yanyiwu/gojieba._Cfunc_NewJieba(0x4500000, 0x4500070, 0x45000e0, 0x0)
	??:0 +0x42 fp=0xc82004dca8 sp=0xc82004dc70
github.com/yanyiwu/gojieba.NewJieba(0x0, 0x0, 0x0, 0x0)
	/Users/hqw/Desktop/gofiles/src/github.com/yanyiwu/gojieba/jieba.go:37 +0x22d fp=0xc82004dda0 sp=0xc82004dca8
main.main()
	/Users/hqw/gojieba.go:14 +0x62 fp=0xc82004df50 sp=0xc82004dda0
runtime.main()
	/usr/local/go/src/runtime/proc.go:188 +0x2b0 fp=0xc82004dfa0 sp=0xc82004df50
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82004dfa8 sp=0xc82004dfa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

rax    0x0
rbx    0x7fff72e77310
rcx    0x7fff5fbff0e8
rdx    0x0
rdi    0x303
rsi    0x6
rbp    0x7fff5fbff110
rsp    0x7fff5fbff0e8
r8     0x4600100
r9     0x0
r10    0x8000000
r11    0x206
r12    0x500000a
r13    0x5000000
r14    0x6
r15    0x7fff74e55398
rip    0x7fff8aead866
rflags 0x206
cs     0x7
fs     0x0
gs     0x72e70000
exit status 2
错误: 进程退出代码 1.

**Comment by yanyiwu** [comment]
是环境变量的问题，在最新版 v0.16.1 中已修复。你试试。

**Comment by Whitehairtoomuch** [comment]
测试成功~感谢

**Comment by cnjeffliu** [comment]
我使用1.1.1版本的gojieba，在一台机器上编译好二进制，在另一台上无法运行，同样报错

**Comment by cnjeffliu** [comment]
@Whitehairtoomuch 请问你使用的go编译选项是什么？
