### ISSUE TITLE
编译项目提高提供的测试代码,回显很多c++编译警告

### ISSUE THREAD

**Issue by ilovesusu** [yanyiwu/gojieba#50]
# github.com/yanyiwu/gojieba
In file included from /home/susu/go/pkg/mod/github.com/yanyiwu/gojieba@v1.0.0/deps/cppjieba/Unicode.hpp:9,
                 from /home/susu/go/pkg/mod/github.com/yanyiwu/gojieba@v1.0.0/deps/cppjieba/DictTrie.hpp:15,
                 from /home/susu/go/pkg/mod/github.com/yanyiwu/gojieba@v1.0.0/deps/cppjieba/QuerySegment.hpp:8,
                 from /home/susu/go/pkg/mod/github.com/yanyiwu/gojieba@v1.0.0/deps/cppjieba/Jieba.hpp:4,
                 from jieba.cpp:5:
/home/susu/go/pkg/mod/github.com/yanyiwu/gojieba@v1.0.0/deps/limonp/LocalVector.hpp: In instantiation of ‘void limonp::LocalVector<T>::reserve(size_t) [with T = std::pair<long unsigned int, const cppjieba::DictUnit*>; size_t = long unsigned int]’:
/home/susu/go/pkg/mod/github.com/yanyiwu/gojieba@v1.0.0/deps/limonp/LocalVector.hpp:83:7:   required from ‘void limonp::LocalVector<T>::push_back(const T&) [with T = std::pair<long unsigned int, const cppjieba::DictUnit*>]’
/home/susu/go/pkg/mod/github.com/yanyiwu/gojieba@v1.0.0/deps/cppjieba/Trie.hpp:99:81:   required from here
/home/susu/go/pkg/mod/github.com/yanyiwu/gojieba@v1.0.0/deps/limonp/LocalVector.hpp:95:11: 警告：‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘struct std::pair<long unsigned int, const cppjieba::DictUnit*>’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
   95 |     memcpy(ptr_, old, sizeof(T) * capacity_);
      |     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/9.1.0/utility:70,
                 from /usr/include/c++/9.1.0/algorithm:60,
                 from /home/susu/go/pkg/mod/github.com/yanyiwu/gojieba@v1.0.0/deps/cppjieba/QuerySegment.hpp:4,
                 from /home/susu/go/pkg/mod/github.com/yanyiwu/gojieba@v1.0.0/deps/cppjieba/Jieba.hpp:4,
                 from jieba.cpp:5:
/usr/include/c++/9.1.0/bits/stl_pair.h:208:12: 附注：‘struct std::pair<long unsigned int, const cppjieba::DictUnit*>’ declared here
  208 |     struct pair
      |            ^~~~
In file included from /home/susu/go/pkg/mod/github.com/yanyiwu/gojieba@v1.0.0/deps/cppjieba/Unicode.hpp:9,
                 from /home/susu/go/pkg/mod/github.com/yanyiwu/gojieba@v1.0.0/deps/cppjieba/DictTrie.hpp:15,
                 from /home/susu/go/pkg/mod/github.com/yanyiwu/gojieba@v1.0.0/deps/cppjieba/QuerySegment.hpp:8,
                 from /home/susu/go/pkg/mod/github.com/yanyiwu/gojieba@v1.0.0/deps/cppjieba/Jieba.hpp:4,
                 from jieba.cpp:5:
/home/susu/go/pkg/mod/github.com/yanyiwu/gojieba@v1.0.0/deps/limonp/LocalVector.hpp: In instantiation of ‘limonp::LocalVector<T>& limonp::LocalVector<T>::operator=(const limonp::LocalVector<T>&) [with T = std::pair<long unsigned int, const cppjieba::DictUnit*>]’:
/home/susu/go/pkg/mod/github.com/yanyiwu/gojieba@v1.0.0/deps/limonp/LocalVector.hpp:33:11:   required from ‘limonp::LocalVector<T>::LocalVector(const limonp::LocalVector<T>&) [with T = std::pair<long unsigned int, const cppjieba::DictUnit*>]’
/home/susu/go/pkg/mod/github.com/yanyiwu/gojieba@v1.0.0/deps/cppjieba/Trie.hpp:28:8:   required from ‘void std::_Construct(_T1*, _Args&& ...) [with _T1 = cppjieba::Dag; _Args = {const cppjieba::Dag&}]’
/usr/include/c++/9.1.0/bits/stl_uninitialized.h:83:18:   required from ‘static _ForwardIterator std::__uninitialized_copy<_TrivialValueTypes>::__uninit_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = const cppjieba::Dag*; _ForwardIterator = cppjieba::Dag*; bool _TrivialValueTypes = false]’
/usr/include/c++/9.1.0/bits/stl_uninitialized.h:134:15:   required from ‘_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = const cppjieba::Dag*; _ForwardIterator = cppjieba::Dag*]’
/usr/include/c++/9.1.0/bits/stl_uninitialized.h:289:37:   required from ‘_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = const cppjieba::Dag*; _ForwardIterator = cppjieba::Dag*; _Tp = cppjieba::Dag]’
/usr/include/c++/9.1.0/bits/stl_uninitialized.h:311:2:   required from ‘_ForwardIterator std::__uninitialized_move_if_noexcept_a(_InputIterator, _InputIterator, _ForwardIterator, _Allocator&) [with _InputIterator = cppjieba::Dag*; _ForwardIterator = cppjieba::Dag*; _Allocator = std::allocator<cppjieba::Dag>]’
/usr/include/c++/9.1.0/bits/vector.tcc:659:48:   required from ‘void std::vector<_Tp, _Alloc>::_M_default_append(std::vector<_Tp, _Alloc>::size_type) [with _Tp = cppjieba::Dag; _Alloc = std::allocator<cppjieba::Dag>; std::vector<_Tp, _Alloc>::size_type = long unsigned int]’
/usr/include/c++/9.1.0/bits/stl_vector.h:937:4:   required from ‘void std::vector<_Tp, _Alloc>::resize(std::vector<_Tp, _Alloc>::size_type) [with _Tp = cppjieba::Dag; _Alloc = std::allocator<cppjieba::Dag>; std::vector<_Tp, _Alloc>::size_type = long unsigned int]’
/home/susu/go/pkg/mod/github.com/yanyiwu/gojieba@v1.0.0/deps/cppjieba/Trie.hpp:86:27:   required from here
/home/susu/go/pkg/mod/github.com/yanyiwu/gojieba@v1.0.0/deps/limonp/LocalVector.hpp:63:13: 警告：‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘struct std::pair<long unsigned int, const cppjieba::DictUnit*>’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
   63 |       memcpy(ptr_, vec.ptr_, vec.size() * sizeof(T));
      |       ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/9.1.0/utility:70,
                 from /usr/include/c++/9.1.0/algorithm:60,
                 from /home/susu/go/pkg/mod/github.com/yanyiwu/gojieba@v1.0.0/deps/cppjieba/QuerySegment.hpp:4,
                 from /home/susu/go/pkg/mod/github.com/yanyiwu/gojieba@v1.0.0/deps/cppjieba/Jieba.hpp:4,
                 from jieba.cpp:5:
/usr/include/c++/9.1.0/bits/stl_pair.h:208:12: 附注：‘struct std::pair<long unsigned int, const cppjieba::DictUnit*>’ declared here
  208 |     struct pair
      |            ^~~~

**Comment by 599020328** [comment]
我也遇到了同样的问题，然后跑示例程序会直接崩溃退出：Process finished with exit code -1073741511 (0xC0000139)

**Comment by AdorableParker** [comment]
几乎一样的问题，但是能够正常执行示范代码，就是在执行前面会抛出一大坨
```
# github.com/yanyiwu/gojieba
In file included from ..\..\..\go\pkg\mod\github.com\yanyiwu\gojieba@v1.1.2\deps/cppjieba/Unicode.hpp:9,
                 from ..\..\..\go\pkg\mod\github.com\yanyiwu\gojieba@v1.1.2\deps/cppjieba/DictTrie.hpp:15,
                 from ..\..\..\go\pkg\mod\github.com\yanyiwu\gojieba@v1.1.2\deps/cppjieba/QuerySegment.hpp:8,
                 from ..\..\..\go\pkg\mod\github.com\yanyiwu\gojieba@v1.1.2\deps/cppjieba/Jieba.hpp:4,
                 from jieba.cpp:5:
..\..\..\go\pkg\mod\github.com\yanyiwu\gojieba@v1.1.2\deps/limonp/LocalVector.hpp: In instantiation of 'void limonp::LocalVector<T>::reserve(size_t) [with T = std::pair<long long unsigned int, const cppjieba::DictUnit*>; size_t = long long unsigned int]':
..\..\..\go\pkg\mod\github.com\yanyiwu\gojieba@v1.1.2\deps/limonp/LocalVector.hpp:83:7:   required from 'void limonp::LocalVector<T>::push_back(const T&) [with T = std::pair<long long unsigned int, const cppjieba::DictUnit*>]'
..\..\..\go\pkg\mod\github.com\yanyiwu\gojieba@v1.1.2\deps/cppjieba/Trie.hpp:99:81:   required from here
..\..\..\go\pkg\mod\github.com\yanyiwu\gojieba@v1.1.2\deps/limonp/LocalVector.hpp:95:11: warning: 'void* memcpy(void*, const void*, size_t)' writing to an object of type 'struct std::pair<long long unsigned int, const cppjieba::DictUnit*>' with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
   95 |     memcpy(ptr_, old, sizeof(T) * capacity_);
      |     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from D:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++/utility:70,
                 from D:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++/algorithm:60,
                 from ..\..\..\go\pkg\mod\github.com\yanyiwu\gojieba@v1.1.2\deps/cppjieba/QuerySegment.hpp:4,
                 from ..\..\..\go\pkg\mod\github.com\yanyiwu\gojieba@v1.1.2\deps/cppjieba/Jieba.hpp:4,
                 from jieba.cpp:5:
D:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++/bits/stl_pair.h:208:12: note: 'struct std::pair<long long unsigned int, const cppjieba::DictUnit*>' declared here
  208 |     struct pair
      |            ^~~~
In file included from ..\..\..\go\pkg\mod\github.com\yanyiwu\gojieba@v1.1.2\deps/cppjieba/Unicode.hpp:9,
                 from ..\..\..\go\pkg\mod\github.com\yanyiwu\gojieba@v1.1.2\deps/cppjieba/DictTrie.hpp:15,
                 from ..\..\..\go\pkg\mod\github.com\yanyiwu\gojieba@v1.1.2\deps/cppjieba/QuerySegment.hpp:8,
                 from ..\..\..\go\pkg\mod\github.com\yanyiwu\gojieba@v1.1.2\deps/cppjieba/Jieba.hpp:4,
                 from jieba.cpp:5:
..\..\..\go\pkg\mod\github.com\yanyiwu\gojieba@v1.1.2\deps/limonp/LocalVector.hpp: In instantiation of 'limonp::LocalVector<T>& limonp::LocalVector<T>::operator=(const limonp::LocalVector<T>&) [with T = std::pair<long long unsigned int, const cppjieba::DictUnit*>]':
..\..\..\go\pkg\mod\github.com\yanyiwu\gojieba@v1.1.2\deps/limonp/LocalVector.hpp:33:11:   required from 'limonp::LocalVector<T>::LocalVector(const limonp::LocalVector<T>&) [with T = std::pair<long long unsigned int, const cppjieba::DictUnit*>]'
..\..\..\go\pkg\mod\github.com\yanyiwu\gojieba@v1.1.2\deps/cppjieba/Trie.hpp:28:8:   required from 'void std::_Construct(_T1*, _Args&& ...) [with _T1 = cppjieba::Dag; _Args = {const cppjieba::Dag&}]'
D:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++/bits/stl_uninitialized.h:83:18:   required from 'static _ForwardIterator std::__uninitialized_copy<_TrivialValueTypes>::__uninit_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = const cppjieba::Dag*; _ForwardIterator = cppjieba::Dag*; bool _TrivialValueTypes = false]'
D:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++/bits/stl_uninitialized.h:134:15:   required from '_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = const cppjieba::Dag*; _ForwardIterator = cppjieba::Dag*]'
D:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++/bits/stl_uninitialized.h:289:37:   required from '_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = const cppjieba::Dag*; _ForwardIterator = cppjieba::Dag*; _Tp = cppjieba::Dag]'
D:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++/bits/stl_uninitialized.h:311:2:   required from '_ForwardIterator std::__uninitialized_move_if_noexcept_a(_InputIterator, _InputIterator, 
_ForwardIterator, _Allocator&) [with _InputIterator = cppjieba::Dag*; _ForwardIterator = cppjieba::Dag*; _Allocator = std::allocator<cppjieba::Dag>]'
D:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++/bits/vector.tcc:659:48:   required from 'void std::vector<_Tp, _Alloc>::_M_default_append(std::vector<_Tp, _Alloc>::size_type) [with _Tp = cppjieba::Dag; _Alloc = std::allocator<cppjieba::Dag>; std::vector<_Tp, _Alloc>::size_type = long long unsigned int]'
D:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++/bits/stl_vector.h:937:4:   required from 'void std::vector<_Tp, _Alloc>::resize(std::vector<_Tp, _Alloc>::size_type) [with _Tp = cppjieba::Dag; _Alloc = std::allocator<cppjieba::Dag>; std::vector<_Tp, _Alloc>::size_type = long long unsigned int]'
..\..\..\go\pkg\mod\github.com\yanyiwu\gojieba@v1.1.2\deps/cppjieba/Trie.hpp:86:27:   required from here
..\..\..\go\pkg\mod\github.com\yanyiwu\gojieba@v1.1.2\deps/limonp/LocalVector.hpp:63:13: warning: 'void* memcpy(void*, const void*, size_t)' writing to an object of type 'struct std::pair<long long unsigned int, const cppjieba::DictUnit*>' with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
   63 |       memcpy(ptr_, vec.ptr_, vec.size() * sizeof(T));
      |       ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from D:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++/utility:70,
                 from D:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++/algorithm:60,
                 from ..\..\..\go\pkg\mod\github.com\yanyiwu\gojieba@v1.1.2\deps/cppjieba/QuerySegment.hpp:4,
                 from ..\..\..\go\pkg\mod\github.com\yanyiwu\gojieba@v1.1.2\deps/cppjieba/Jieba.hpp:4,
                 from jieba.cpp:5:
D:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++/bits/stl_pair.h:208:12: note: 'struct std::pair<long long unsigned int, const cppjieba::DictUnit*>' declared here
  208 |     struct pair
      |            ^~~~
我来到北京清华大学
全模式: 我/来到/北京/清华/清华大学/华大/大学
我来到北京清华大学
精确模式: 我/来到/北京/清华大学
比特币
精确模式: 比特/币
比特币
添加词典后,精确模式: 比特币
他来到了网易杭研大厦
新词识别: 他/来到/了/网易/杭研/大厦
小明硕士毕业于中国科学院计算所，后在日本京都大学深造
搜索引擎模式: 小明/硕士/毕业/于/中国/科学/学院/科学院/中国科学院/计算/计算所/，/后/在/日本/京都/大学/日本京都大学/深造
长春市长春药店
区块链
词性标注: 区块链/nz
长江大桥
搜索引擎模式: 长江/大桥/长江大桥
长江大桥
Tokenize:(搜索引擎模式) [{长江 0 6} {大桥 6 12} {长江大桥 0 12}]
长江大桥
Tokenize:(默认模式) [{长江大桥 0 12}]
Extract: [{长江大桥 11.1926274509}]
```

**Comment by SnowPhoenix0105** [comment]
fork一份，然后jieba.go中【#cgo CXXFLAGS: -I./deps -DLOGGING_LEVEL=LL_WARNING -O3 -Wall】改成【#cgo CXXFLAGS: -I./deps -DLOGGING_LEVEL=LL_WARNING -O3 -w】，然后打一个tag，然后go.mod加一个replace重定向到自己fork的仓库
