### ISSUE TITLE
你好，安装之后运行不成功

### ISSUE THREAD

**Issue by xingzhe1228** [yanyiwu/gojieba#51]
2019-08-21 09:53:57 /home/lxx/code/go/src/di/marmot/vendor/github.com/yanyiwu/gojieba/deps/cppjieba/HMMModel.hpp:43 FATAL exp: [tmp.size() == STATUS_SUM] false. 
SIGABRT: abort
PC=0x7f64097961d7 m=11 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0xa04010, 0xc420057970, 0xc420057978)
	/usr/lib/golang/src/runtime/cgocall.go:132 +0xe4 fp=0xc420057940 sp=0xc420057900 pc=0x409ff4
di/marmot/vendor/github.com/yanyiwu/gojieba._Cfunc_NewJieba(0x7f63e00008c0, 0x7f63e00008f0, 0x7f63e0000920, 0x7f63e0000990, 0x7f63e0000a00, 0x0)
	di/marmot/vendor/github.com/yanyiwu/gojieba/_obj/_cgo_gotypes.go:214 +0x4e fp=0xc420057970 sp=0xc420057940 pc=0x80ba9e
di/marmot/vendor/github.com/yanyiwu/gojieba.NewJieba(0xc429e235e0, 0x2, 0x2, 0x0)
	/home/lxx/code/go/src/di/marmot/vendor/github.com/yanyiwu/gojieba/jieba.go:37 +0x268 fp=0xc420057a70 sp=0xc420057970 pc=0x80c088
di/marmot/nlp.NewFeatureSegmenter(0xc429e235e0, 0x2, 0x2, 0x1)
	/home/lxx/code/go/src/di/marmot/nlp/feature_segment.go:10 +0x43 fp=0xc420057ab0 sp=0xc420057a70 pc=0x83f5c3
di/marmot/adserver/route.NewRestAPI(0xc420037c00, 0xc420087a90)
	/home/lxx/code/go/src/di/marmot/adserver/route/rest_api.go:176 +0xf42 fp=0xc420057e78 sp=0xc420057ab0 pc=0x9e9ea2
main.main()
	/home/lxx/code/go/src/di/marmot/adserver/main.go:27 +0x2ef fp=0xc420057f80 sp=0xc420057e78 pc=0xa0307f
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:195 +0x226 fp=0xc420057fe0 sp=0xc420057f80 pc=0x4344d6
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420057fe8 sp=0xc420057fe0 pc=0x460a31

rax    0x0
rbx    0x7f6404df5920
rcx    0xffffffffffffffff
rdx    0x6
rdi    0x3da0
rsi    0x3daa
rbp    0x7f6404df5510
rsp    0x7f6404df53c8
r8     0x1
r9     0x7f6404df7700
r10    0x8
r11    0x206
r12    0x7f640a3b9140
r13    0x7f640a3b7dc0
r14    0x7f63e0000dc0
r15    0x7f6404df5580
rip    0x7f64097961d7
rflags 0x206
cs     0x33
fs     0x0
gs     0x0

**Comment by xingzhe1228** [comment]
go version go1.9.4 linux/amd64

**Comment by xingzhe1228** [comment]
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/lxx/code/go"
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build211024074=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

**Comment by YogeLiu** [comment]
请问解决了吗

**Comment by githubzhaoqian** [comment]
字典格式改成试试
云计算 1 n
韩玉鉴赏 1 n
你好吗 1 n

**Comment by githubzhaoqian** [comment]
@yanyiwu  字典格式现在必须带上 数字和词性了
