### ISSUE TITLE
用 Go 实现核心功能会有问题吗

### ISSUE THREAD

**Issue by mofadeyunduo** [yanyiwu/gojieba#57]
```
核心算法底层由C++实现，性能高效
```
为什么这么说？是因为内存释放的问题吗？

**Comment by yanyiwu** [comment]
用 Go 实现核心功能会有问题吗?没有问题。
只是说c++目前来看，性能还是高于golang。但是可能差距也没那么大。具体需要评估。

**Comment by mofadeyunduo** [comment]
thx，提这个问题主要是因为公司想用一个比较纯的 golang 去实现，毕竟官方也说了，用 cgo 不是一个很好的做法（不像是在用 go 语言），除非在迫不得已的情况下
