### ISSUE TITLE
关键词提取的时候可以返回权重么

### ISSUE THREAD

**Issue by safeie** [yanyiwu/gojieba#6]
类似jieba python标准版中的，用法示例：https://github.com/fxsjy/jieba/blob/master/test/extract_tags_with_weight.py

权重对于提取出来的词进一步计算还是有很大作用的。感谢。

**Comment by yanyiwu** [comment]
@safeie v0.17.0 里面新增 ExtractWithWeight 函数可以返回带权重的。

**Comment by safeie** [comment]
thank you.
