### ISSUE TITLE
macos can't find stdlib.h

### ISSUE THREAD

**Issue by cooscao** [yanyiwu/gojieba#64]
When I run my code, error occurs as follow:
`# github.com/yanyiwu/gojieba
../../go/pkg/mod/github.com/yanyiwu/gojieba@v1.1.1/jieba.go:5:10: fatal error: 'stdlib.h' file not found
#include <stdlib.h>
         ^~~~~~~~~~
1 error generated.`
my system is macos Catalina,how to solove this?

**Comment by Freakwill** [comment]
The same error

**Comment by tuxi** [comment]
xcode-select --install
