### ISSUE TITLE
在beego中使用打包报错

### ISSUE THREAD

**Issue by zone-7** [yanyiwu/gojieba#71]
执行打包指令： bee pack -be GOOS=linux -be GOARCH=amd64 
出现下面报错：

2020/07/04 10:55:40 INFO     ▶ 0003 Using: GOOS=linux GOARCH=amd64
#test/service
service/MethineService.go:121:9: undefined: gojieba.NewJieba
service/ModelService.go:22:9: undefined: gojieba.NewJieba
2020/07/04 10:55:41 FATAL    ▶ 0004 exit status 2

我是错在哪个环节了？

**Comment by GendSmith** [comment]
我也遇到一样的问题，，，

**Comment by alpiny** [comment]
因为使用的go编辑器，不能编译C，gojieba调用了C。设置 CGO_ENABLED=1 再编译试试。如果报其他错误，说明你遇到了和我一样的问题，逃。。。

**Comment by Hanggi** [comment]
有什么解决或者替代方案吗？

**Comment by HQ1363** [comment]
mac 系统不支持,换到 linux 环境下, 再 pack, 就没问题了

**Comment by chaegumi** [comment]
2023年，我今天构建了也不行，一样的问题
controllers\gojieba.go:24:7: undefined: gojieba.NewJieba
controllers\gojieba.go:74:29: undefined: gojieba.SearchMode
controllers\gojieba.go:78:28: undefined: gojieba.DefaultMode
controllers\gojieba.go:101:7: undefined: gojieba.NewJieba
