### ISSUE TITLE
在添加用户词典后，词性标注不正常

### ISSUE THREAD

**Issue by nick-lee** [yanyiwu/gojieba#72]
在实例化的时候引入了自定义字典：
jb  = gojieba.NewJieba("./dicts/dict.txt")
然后再使用例子的时候，所有词性标注的地方，如果不是字典里面定义过的，均标识为"x" :

s = "长春市长春药店"                                                                                                 
words = x.Tag(s)                                                                                                     
fmt.Println(s)                                                                                                       
fmt.Println("词性标注:", strings.Join(words, ","))

长春市长春药店                                                                
词性标注: 长春市/x,长春药店/x

如果实例化的时候不引入自定义字典文件，结果是正常的。
我理解可能是引入自定义词典的时候，系统会忽略默认词典的标识，不知道哪位高人有没有思路如何解决这个问题?

**Comment by JankinHou** [comment]
我引入词典后直接不能分词了。。。。

**Comment by xionglei2** [comment]
`func getDictPaths(args ...string) [TOTAL_DICT_PATH_NUMBER]string {
	dicts := [TOTAL_DICT_PATH_NUMBER]string{
		DICT_PATH,
		HMM_PATH,
		USER_DICT_PATH,
		IDF_PATH,
		STOP_WORDS_PATH,
	}
	for i := 0; i < len(args) && i < len(dicts); i++ {
		dicts[i] = args[i]
	}
	return dicts
}`

你把真正的dict给覆盖了
