### ISSUE TITLE
Got messy warning information when getting gojieba

### ISSUE THREAD

**Issue by Freakwill** [yanyiwu/gojieba#76]
Got following warning when executing `go get github.com/yanyiwu/gojieba`

# github.com/yanyiwu/gojieba
In file included from jieba.cpp:5:
In file included from /usr/local/Cellar/go/1.15.5/src/github.com/yanyiwu/gojieba/deps/cppjieba/Jieba.hpp:4:
In file included from /usr/local/Cellar/go/1.15.5/src/github.com/yanyiwu/gojieba/deps/cppjieba/QuerySegment.hpp:8:
In file included from /usr/local/Cellar/go/1.15.5/src/github.com/yanyiwu/gojieba/deps/cppjieba/DictTrie.hpp:11:
/usr/local/opt/llvm/bin/../include/c++/v1/cmath:317:9: error: no member named 'signbit' in the global namespace
/usr/local/opt/llvm/bin/../include/c++/v1/cmath:318:9: error: no member named 'fpclassify' in the global namespace
/usr/local/opt/llvm/bin/../include/c++/v1/cmath:319:9: error: no member named 'isfinite' in the global namespace; did you mean 'finite'?
/usr/local/include/c++/v1/math.h:752:12: note: 'finite' declared here
In file included from jieba.cpp:5:
In file included from /usr/local/Cellar/go/1.15.5/src/github.com/yanyiwu/gojieba/deps/cppjieba/Jieba.hpp:4:
In file included from /usr/local/Cellar/go/1.15.5/src/github.com/yanyiwu/gojieba/deps/cppjieba/QuerySegment.hpp:8:
In file included from /usr/local/Cellar/go/1.15.5/src/github.com/yanyiwu/gojieba/deps/cppjieba/DictTrie.hpp:11:
/usr/local/opt/llvm/bin/../include/c++/v1/cmath:320:9: error: no member named 'isinf' in the global namespace
/usr/local/opt/llvm/bin/../include/c++/v1/cmath:321:9: error: no member named 'isnan' in the global namespace
/usr/local/opt/llvm/bin/../include/c++/v1/cmath:322:9: error: no member named 'isnormal' in the global namespace
/usr/local/opt/llvm/bin/../include/c++/v1/cmath:323:7: error: no member named 'isgreater' in the global namespace; did you mean '::std::greater'?
/usr/local/opt/llvm/bin/../include/c++/v1/functional:738:29: note: '::std::greater' declared here
In file included from jieba.cpp:5:
In file included from /usr/local/Cellar/go/1.15.5/src/github.com/yanyiwu/gojieba/deps/cppjieba/Jieba.hpp:4:
In file included from /usr/local/Cellar/go/1.15.5/src/github.com/yanyiwu/gojieba/deps/cppjieba/QuerySegment.hpp:8:
In file included from /usr/local/Cellar/go/1.15.5/src/github.com/yanyiwu/gojieba/deps/cppjieba/DictTrie.hpp:11:
/usr/local/opt/llvm/bin/../include/c++/v1/cmath:324:7: error: no member named 'isgreaterequal' in the global namespace; did you mean '::std::greater_equal'?
/usr/local/opt/llvm/bin/../include/c++/v1/functional:767:29: note: '::std::greater_equal' declared here
In file included from jieba.cpp:5:
In file included from /usr/local/Cellar/go/1.15.5/src/github.com/yanyiwu/gojieba/deps/cppjieba/Jieba.hpp:4:
In file included from /usr/local/Cellar/go/1.15.5/src/github.com/yanyiwu/gojieba/deps/cppjieba/QuerySegment.hpp:8:
In file included from /usr/local/Cellar/go/1.15.5/src/github.com/yanyiwu/gojieba/deps/cppjieba/DictTrie.hpp:11:
/usr/local/opt/llvm/bin/../include/c++/v1/cmath:325:9: error: no member named 'isless' in the global namespace
/usr/local/opt/llvm/bin/../include/c++/v1/cmath:326:9: error: no member named 'islessequal' in the global namespace
/usr/local/opt/llvm/bin/../include/c++/v1/cmath:327:9: error: no member named 'islessgreater' in the global namespace
/usr/local/opt/llvm/bin/../include/c++/v1/cmath:328:9: error: no member named 'isunordered' in the global namespace
/usr/local/opt/llvm/bin/../include/c++/v1/cmath:329:9: error: no member named 'isunordered' in the global namespace
In file included from jieba.cpp:5:
In file included from /usr/local/Cellar/go/1.15.5/src/github.com/yanyiwu/gojieba/deps/cppjieba/Jieba.hpp:4:
In file included from /usr/local/Cellar/go/1.15.5/src/github.com/yanyiwu/gojieba/deps/cppjieba/QuerySegment.hpp:8:
In file included from /usr/local/Cellar/go/1.15.5/src/github.com/yanyiwu/gojieba/deps/cppjieba/DictTrie.hpp:13:
/usr/local/Cellar/go/1.15.5/src/github.com/yanyiwu/gojieba/deps/limonp/StringUtil.hpp:87:70: warning: 'ptr_fun<unsigned int, bool>' is deprecated [-Wdeprecated-declarations]
/usr/local/opt/llvm/bin/../include/c++/v1/functional:1107:1: note: 'ptr_fun<unsigned int, bool>' has been explicitly marked deprecated here
/usr/local/opt/llvm/bin/../include/c++/v1/__config:972:39: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX11'
/usr/local/opt/llvm/bin/../include/c++/v1/__config:961:48: note: expanded from macro '_LIBCPP_DEPRECATED'
In file included from jieba.cpp:5:
In file included from /usr/local/Cellar/go/1.15.5/src/github.com/yanyiwu/gojieba/deps/cppjieba/Jieba.hpp:4:
In file included from /usr/local/Cellar/go/1.15.5/src/github.com/yanyiwu/gojieba/deps/cppjieba/QuerySegment.hpp:8:
In file included from /usr/local/Cellar/go/1.15.5/src/github.com/yanyiwu/gojieba/deps/cppjieba/DictTrie.hpp:13:
/usr/local/Cellar/go/1.15.5/src/github.com/yanyiwu/gojieba/deps/limonp/StringUtil.hpp:92:61: warning: 'ptr_fun<unsigned int, bool>' is deprecated [-Wdeprecated-declarations]
/usr/local/opt/llvm/bin/../include/c++/v1/functional:1107:1: note: 'ptr_fun<unsigned int, bool>' has been explicitly marked deprecated here
/usr/local/opt/llvm/bin/../include/c++/v1/__config:972:39: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX11'
/usr/local/opt/llvm/bin/../include/c++/v1/__config:961:48: note: expanded from macro '_LIBCPP_DEPRECATED'
In file included from jieba.cpp:5:
In file included from /usr/local/Cellar/go/1.15.5/src/github.com/yanyiwu/gojieba/deps/cppjieba/Jieba.hpp:4:
In file included from /usr/local/Cellar/go/1.15.5/src/github.com/yanyiwu/gojieba/deps/cppjieba/QuerySegment.hpp:8:
In file included from /usr/local/Cellar/go/1.15.5/src/github.com/yanyiwu/gojieba/deps/cppjieba/DictTrie.hpp:13:
/usr/local/Cellar/go/1.15.5/src/github.com/yanyiwu/gojieba/deps/limonp/StringUtil.hpp:101:70: warning: 'bind2nd<std::__1::equal_to<char>, char>' is deprecated [-Wdeprecated-declarations]
/usr/local/opt/llvm/bin/../include/c++/v1/functional:1089:1: note: 'bind2nd<std::__1::equal_to<char>, char>' has been explicitly marked deprecated here
/usr/local/opt/llvm/bin/../include/c++/v1/__config:972:39: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX11'
/usr/local/opt/llvm/bin/../include/c++/v1/__config:961:48: note: expanded from macro '_LIBCPP_DEPRECATED'
In file included from jieba.cpp:5:
In file included from /usr/local/Cellar/go/1.15.5/src/github.com/yanyiwu/gojieba/deps/cppjieba/Jieba.hpp:4:
In file included from /usr/local/Cellar/go/1.15.5/src/github.com/yanyiwu/gojieba/deps/cppjieba/QuerySegment.hpp:8:
In file included from /usr/local/Cellar/go/1.15.5/src/github.com/yanyiwu/gojieba/deps/cppjieba/DictTrie.hpp:13:
/usr/local/Cellar/go/1.15.5/src/github.com/yanyiwu/gojieba/deps/limonp/StringUtil.hpp:106:61: warning: 'bind2nd<std::__1::equal_to<char>, char>' is deprecated [-Wdeprecated-declarations]
/usr/local/opt/llvm/bin/../include/c++/v1/functional:1089:1: note: 'bind2nd<std::__1::equal_to<char>, char>' has been explicitly marked deprecated here
/usr/local/opt/llvm/bin/../include/c++/v1/__config:972:39: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX11'
/usr/local/opt/llvm/bin/../include/c++/v1/__config:961:48: note: expanded from macro '_LIBCPP_DEPRECATED'

**Comment by housemecn** [comment]
这个不影响使用，10.15刚开始有问题，后面正常，现在升级到11的系统 又出现这个问题 但是使用的时候是正常的！
