### ISSUE TITLE
增加单词的词性、权重属性

### ISSUE THREAD

**Issue by koalacxr** [yanyiwu/gojieba#9]
type WordWeight struct {
    Word   string
    Weight float64
    Tag    string
}

word weight改成WordProperty 

最好是所有模式分词出来的，都带有词频、词性 等属性

**Comment by koalacxr** [comment]
type WordWeight struct {
Word string
Weight float64
Tag string
Count int64   //出现次数
}

增加出现次数

**Comment by yanyiwu** [comment]
这个后来想了想，一般都需要二次封装。还是上层使用者按照需求自己封装吧，比如 Count 字段之类的。并不是都需要的。
