### ISSUE TITLE
x.AddWord之后，希望增加x.RemoveWord的功能

### ISSUE THREAD

**Issue by AydenZ** [yanyiwu/gojieba#97]
需求背景：
管理员后台动态增加keyword,
Jieba 使用x.addWord(keyword)

当管理员删除keyword的时候
Jieba 无相关api删除这个keyword

期待您有时间考虑下这个需求。

**Comment by AydenZ** [comment]
已提交PR:
https://github.com/yanyiwu/gojieba/pull/99

**Comment by yanyiwu** [comment]
Merged
